title:            Chasing the light
description:      Just another home on the internet.
url:              http://supergrubby.com/
signoff:          supergrubby
disqus_shortname: #
facebook_appid:   #
google_analytics: #
links: 
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://supergrubby.com
    external:     true
  - name:         Email
    url:          mailto:supergrubby@foxmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/supergrubby
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
